
-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 19:20:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  id BIGINT AUTO_INCREMENT,
  `massa` VARCHAR(255) NOT NULL,
  `sabor` VARCHAR(255) NOT NULL,
  `borda` VARCHAR(255) NOT NULL,
  `bebida` VARCHAR(255) NOT NULL,
  `valor` INT NOT NULL,
  `tb_categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `tb_categoria_id`),
  INDEX `fk_tb_pizza_tb_categoria_idx` (`tb_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_tb_categoria`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `massa_fina` VARCHAR(255) NOT NULL,
  `massa_grossa` VARCHAR(255) NOT NULL,
  `borda` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
   id INT AUTO_INCREMENT PRIMARY KEY,
  `massa` VARCHAR(255) NOT NULL,
  `sabor` VARCHAR(255) NOT NULL,
  `borda` VARCHAR(255) NOT NULL,
  `bebida` VARCHAR(255) NOT NULL,
  `valor` INT NOT NULL,
  `tb_categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `tb_categoria_id`),
  INDEX `fk_tb_pizza_tb_categoria_idx` (`tb_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pizza_tb_categoria`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_categoria (massa_fina, massa_grossa, borda)
VALUES ("Não", "Sim", "Sim");

INSERT INTO tb_categoria (massa_fina, massa_grossa, borda)
VALUES ("Sim", "Não", "Não");

INSERT INTO tb_categoria (massa_fina, massa_grossa, borda)
VALUES ("Sim", "Não", "Sim");

INSERT INTO tb_categoria (massa_fina, massa_grossa, borda)
VALUES ("Sim", "Não", "Sim");

INSERT INTO tb_categoria (massa_fina, massa_grossa, borda)
VALUES ("Não", "Sim", "Sim");

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Integral", "Abrobrinha queijo de fubalo", "Sim cheddar", "Sim suco de uva", 120, 1);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Normal", "Frango com catupury", "Nao", "Não", 55.00, 5);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Normal", "Portuguesa", "Nao", "Não", 48.00, 6);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Integral", "Banana com chocolate", "Nao","Não", 35.00, 1);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Normal", "Mussarela", "Nao", "Não", 25.00, 1);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Normal", "Calabresa", "Nao", "Não", 27.00, 1);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Normal", "Peru com mussarela", "Nao", "Sim", 36.00, 5);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Integral", "Brocolis com bacon e queijo de cabra", "Nao", "Não", 120.00, 5);

INSERT INTO tb_pizza (massa, sabor, borda, bebida, valor, tb_categoria_id)
VALUES ("Integral", "Abrobrinha com queijo de fubalo", "Nao", "Não", 80.00, 6);

SELECT * FROM tb_pizza WHERE valor > 45.00;

SELECT * FROM tb_pizza WHERE valor between 29.00 and 60.00;

SELECT * FROM tb_pizza WHERE massa LIKE 'i%';

SELECT 
	*
FROM 
	tb_categoria
	INNER JOIN tb_pizza 
		ON tb_categoria.id = tb_pizza.tb_categoria_id;

SELECT * FROM tb_categoria WHERE massa_grossa = "Sim";


